# Generated by Django 4.2.23 on 2025-08-07 15:38

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('user_first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a profile picture.', max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
