# Generated by Django 4.2.23 on 2025-08-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tasks_quota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
