# Generated by Django 4.2.23 on 2025-08-29 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0002_order_unique_default_address_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, unique=True)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(max_length=255)),
                ('plan_code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'active'), ('trialing', 'trialing'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired'), ('unpaid', 'unpaid'), ('paused', 'paused')], max_length=32)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
