# Generated by Django 4.2.23 on 2025-08-29 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
