# Generated by Django 4.2.23 on 2025-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_rewardhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardhistory',
            name='reward_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reward',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Number of items available for this reward.'),
        ),
    ]
