# Generated by Django 4.2.23 on 2025-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_rewardhistory_reward_sent_alter_reward_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
