# Generated by Django 4.2.23 on 2025-09-05 17:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_alter_reward_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='available_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('FR', 'France'), ('DE', 'Germany'), ('ES', 'Spain'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('NO', 'Norway'), ('FI', 'Finland'), ('DK', 'Denmark'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('IE', 'Ireland'), ('PT', 'Portugal'), ('GR', 'Greece'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('HR', 'Croatia'), ('SI', 'Slovenia'), ('SK', 'Slovakia')], max_length=68, null=True, verbose_name='Reward available in Countries'),
        ),
    ]
