# Generated by Django 4.2.23 on 2025-09-07 12:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_reward_available_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='available_countries',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Everywhere', 'Everywhere'), ('France', 'France'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Ireland', 'Ireland'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia')], max_length=204, null=True, verbose_name='Reward available in Countries'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('digital', 'Digital'), ('discount', 'Discount Code'), ('travel', 'Travel'), ('wellness', 'Wellness'), ('food', 'Food'), ('fashion', 'Fashion'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50, verbose_name='Reward Type'),
        ),
    ]
