# Generated by Django 4.2.23 on 2025-09-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_reward_available_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('Digital', 'Digital'), ('Discount Code', 'Discount Code'), ('Travel', 'Travel'), ('Wellness', 'Wellness'), ('Food', 'Food'), ('Electronics', 'Electronics'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=50, verbose_name='Reward Type'),
        ),
    ]
