# Generated by Django 4.2.23 on 2025-09-07 18:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='available_countries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Everywhere', 'Everywhere'), ('France', 'France'), ('Germany', 'Germany'), ('Spain', 'Spain'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Denmark', 'Denmark'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Ireland', 'Ireland'), ('Portugal', 'Portugal'), ('Greece', 'Greece'), ('Poland', 'Poland'), ('Czech Republic', 'Czech Republic'), ('Hungary', 'Hungary'), ('Romania', 'Romania'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Slovenia', 'Slovenia'), ('Slovakia', 'Slovakia')], default=['Everywhere'], max_length=204, verbose_name='Reward available in Countries'),
        ),
    ]
