# Generated by Django 4.2.23 on 2025-09-07 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0008_alter_reward_available_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardhistory',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_history', to='rewards.reward'),
        ),
        migrations.AlterField(
            model_name='rewardhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
