# Generated by Django 4.2.23 on 2025-08-06 21:47

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('goal_description', models.TextField(help_text='Describe the goal of this task.', max_length=500)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repetition', models.BooleanField(default=False)),
                ('interval', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='weekly', max_length=10)),
                ('fee', models.DecimalField(decimal_places=2, help_text='Fee for failing this task.', max_digits=10)),
                ('points', models.PositiveIntegerField(help_text='Points awarded for completing this task.')),
                ('checkup_date', models.DateField(blank=True, help_text='Next checkup date for this task.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Checkup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this checkup.', max_length=255, null=True, verbose_name='image')),
                ('text_file', cloudinary.models.CloudinaryField(blank=True, help_text='Upload a text file for this checkup.', max_length=255, null=True, verbose_name='text_file')),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, help_text='Upload an audio file for this checkup.', max_length=255, null=True, verbose_name='audio_file')),
                ('comments', models.TextField(blank=True, help_text='Add any comments for this checkup.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('delete_after_days', models.PositiveIntegerField(default=30)),
                ('deleted', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkups', to='tasks.task')),
            ],
        ),
    ]
