# Generated by Django 4.2.23 on 2025-08-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee for failing this task.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(blank=True, help_text='Points awarded for completing this task.', null=True),
        ),
    ]
