# Generated by Django 4.2.23 on 2025-08-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_userpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='points',
            field=models.PositiveIntegerField(help_text='Total points earned by the user.'),
        ),
    ]
