# Generated by Django 4.2.23 on 2025-08-19 13:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_userpoints_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_checkup',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an audio file for this checkup.', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='text_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a text file for this checkup.', max_length=255, null=True, verbose_name='raw'),
        ),
    ]
