# Generated by Django 4.2.23 on 2025-08-19 18:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_checkup_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_checkup',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an audio file for this checkup.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this checkup.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='text_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a text file for this checkup.', max_length=255, null=True),
        ),
    ]
