# Generated by Django 4.2.23 on 2025-08-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_checkup_audio_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fee_to_pay',
            field=models.BooleanField(default=False),
        ),
    ]
