# Generated by Django 4.2.23 on 2025-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_fee_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fee_payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='penalty_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
