# Generated by Django 4.2.23 on 2025-09-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_checkup_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='checkup_state',
        ),
    ]
