# Generated by Django 4.2.23 on 2025-09-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_task_checkup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='checkup_state',
            field=models.BooleanField(default=False),
        ),
    ]
