# Generated by Django 4.2.23 on 2025-09-07 12:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_task_checkup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkup',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video for this checkup.', max_length=255, null=True),
        ),
    ]
