# Generated by Django 4.2.23 on 2025-09-07 14:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_checkup_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='task',
            name='interval',
            field=models.CharField(choices=[('weekly', 'Weekly / In a week'), ('biweekly', 'Biweekly / In two weeks'), ('monthly', 'Monthly / In a month')], default='weekly', max_length=10),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an audio file for this checkup', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='comments',
            field=models.TextField(blank=True, help_text='Add a comment for this checkup', null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload an image for this checkup', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='text_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a text file for this checkup', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task_checkup',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video for this checkup', max_length=255, null=True),
        ),
    ]
